#!/usr/bin/env bash

path=$1
if [ "" == "$1" ]; then
  path=~/downloads/fontello-*
fi

echo "watching for $path"

extract()
{
  for file in $path; do
    if [ ! -f $file ]; then
      return
    fi
    directory=$(basename ${file%.*})
    echo "processing $directory"
    unzip -qq $file
    cp -v $directory/LICENSE.* ./
    cp -v $directory/config.json ./
    rm -rf $file
    rm -rf ./$directory
  done
}

main()
{
  while true; do
    extract
    sleep 5
  done
}

main
